apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api-deployment
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: client
        tier: backend
    spec:
      containers:
        - name: client
          image: peswafinance/taryareloaded-tenant
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: privatedockerhub

---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
    tier: backend
spec:
  selector:
    app: client
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080